import {
  AccountBalance,
  AccountBalanceWallet,
  AccountCircle,
  AccountTree,
  Assessment,
  AssignmentInd,
  Badge,
  Balance,
  Business,
  BusinessCenter,
  Calculate,
  CalendarMonth,
  CheckCircle,
  Contacts,
  DashboardCustomize,
  DeleteForever,
  Description,
  FolderSpecial,
  Handshake,
  Insights,
  Inventory,
  Login,
  ManageAccounts,
  Paid,
  Payment,
  People,
  Person,
  PersonSearch,
  PieChart,
  PointOfSale,
  ReceiptLong,
  RequestQuote,
  Savings,
  Send,
  SettingsApplications,
  Summarize,
  SwapHoriz,
  Today,
  TrendingUp,
  Wallet,
} from "@mui/icons-material";

export const sidebarGroups = [
  {
    key: "master",
    label: "Master Info",
    icon: ManageAccounts,
    match: ["/main_personal_file", "/loan", "/customer", "/employee", "/partner", "/vendor"],
    items: [
      { label: "Personal Info", path: "/Main_personal_file", icon: Contacts },
      { label: "Loans", path: "/Loan", icon: RequestQuote },
    ],
  },
  {
    key: "transactions",
    label: "Transactions",
    icon: SwapHoriz,
    match: ["/bussinesscashbook_main", "/transactions/"],
    items: [
      { label: "Business Cash Book", path: "/BussinessCashBook_Main", icon: AccountBalanceWallet },
      { label: "Quick Cash Book", path: "/Transactions/Quick_Cash_Book", icon: PointOfSale },
      { label: "Cashbook", path: "/Transactions/Cashbook", icon: Wallet },
      { label: "Delete Transaction", path: "/Transactions/Deleete_Transaction", icon: DeleteForever, danger: true },
    ],
  },
  {
    key: "accounts",
    label: "Accounts",
    icon: AccountBalance,
    match: ["/accountsmodules/"],
    items: [
      { label: "Loans Main", path: "/AccountsModules/LoansMainpage", icon: RequestQuote },
      { label: "Daily Book", path: "/AccountsModules/DailyBook", icon: CalendarMonth },
      { label: "CB Ledger", path: "/AccountsModules/Cbledger", icon: Calculate },
      { label: "Account Ledger", path: "/AccountsModules/AccountLedger", icon: ReceiptLong },
      { label: "Account Master Ledger", path: "/AccountsModules/AccountMasterLedger", icon: FolderSpecial },
      { label: "User Collection Ledger", path: "/AccountsModules/Usercollectionledger", icon: People },
      { label: "Receipt Ledger", path: "/AccountsModules/ReciptLedger", icon: Paid },
    ],
  },
  {
    key: "loan",
    label: "Loans",
    icon: RequestQuote,
    match: ["/loans/"],
    items: [
      { label: "Distributed Loans", path: "/Loans/Distubuted", icon: TrendingUp },
      { label: "Instalment Dues", path: "/Loans/InstalmentDues", icon: Payment },
      { label: "Maturity", path: "/Loans/Maturity", icon: CheckCircle },
    ],
  },
  {
    key: "accountMaster",
    label: "Account Master",
    icon: SettingsApplications,
    match: ["/accountmastersetup/"],
    items: [
      { label: "Account Setup", path: "/AccountMasterSetup/Account_Master_Setup", icon: ManageAccounts },
      { label: "User Registration", path: "/AccountMasterSetup/Registraion_creation", icon: AssignmentInd },
    ],
  },
  {
    key: "business",
    label: "Business",
    icon: BusinessCenter,
    match: ["/bussiness/"],
    items: [
      { label: "Revenue Expense Statement", path: "/Bussiness/RevenueExpenseStatment", icon: Assessment },
      { label: "Balance Sheet", path: "/Bussiness/BalanceSheetimport", icon: Balance },
      { label: "Business Overview", path: "/Bussiness/BussinessOverviewimport", icon: DashboardCustomize },
      { label: "Collection Reports", path: "/Bussiness/BussinessCollectionReportsimport", icon: Assessment },
      { label: "Business Share", path: "/Bussiness/BussinessShare", icon: PieChart },
    ],
  },
  {
    key: "customer",
    label: "Customer Reports",
    icon: PersonSearch,
    match: ["/customer/"],
    items: [
      { label: "Customer Dues", path: "/Customer/Customer_Dues", icon: Today },
      { label: "Outstanding", path: "/Customer/Customer_Outstanding", icon: AccountBalanceWallet },
      { label: "Customer Report", path: "/Customer/Customer_Report", icon: Summarize },
      { label: "Transactions", path: "/Customer/Customer_Transactions", icon: SwapHoriz },
    ],
  },
  {
    key: "partners",
    label: "Partners",
    icon: Handshake,
    match: ["/partners/"],
    items: [
      { label: "Business Reports", path: "/Partners/Bussiness_Reports", icon: Business },
      { label: "Group Business Details", path: "/Partners/Group_Bussiness_Details", icon: Inventory },
      { label: "Group Business", path: "/Partners/Group_Bussiness", icon: AccountTree },
      { label: "Installment Dues", path: "/Partners/Installment_Dues", icon: Payment },
      { label: "Partner Loan Limit", path: "/Partners/Partner_Loan_Limit", icon: Savings },
      { label: "Partner Settlement", path: "/Partners/Partner_Settelment", icon: CheckCircle },
      { label: "Partner Information", path: "/Partners/Partner_Infoamtion", icon: People },
      { label: "Performance", path: "/Partners/Performance", icon: TrendingUp },
    ],
  },
  {
    key: "auth",
    label: "Authentication",
    icon: AccountCircle,
    match: ["/login"],
    items: [{ label: "Sign In", path: "/login", icon: Login }],
  },
];
